### ISSUE TITLE
second HELP line for metric name

### ISSUE THREAD

**Issue by mrobbert** [richardelling/zpool_prometheus#8]
I'm writing the output of zpool_prometheus to a file and reading that file with node_exporter (version 0.18.1) and the parsing of the file is failing with the following error:

May 21 08:18:22 pct-hanas-1.mines.edu node_exporter[123282]: time="2020-05-21T08:18:22-06:00" level=error msg="Error parsing \"/var/lib/node_exporter/zpool_prometheus.prom\": text format parsing error in line 41: second HELP line for metric name \"zpool_stats_state\"" source="textfile.go:211"

I've done a little research and found a similar bug elsewhere where it was stated that rules on HELP lines may have changed and there should be only one HELP line per metric name. I have manually removed the HELP line in question to confirm that the parsing does move forward, but I have a large setup with many vdevs so I haven't taken the time to manually remove all the extra HELP lines. I am looking at the code to see if I can figure out how to change it to meet the needs of the new node_exporter versions.

**Comment by richardelling** [comment]
egads, yep this is an easy fix. I'll prepare a fix.

**Comment by centromere** [comment]
@richardelling Thanks for looking in to this. I am new to Prometheus. What is the proper solution?

**Comment by richardelling** [comment]
I'll be working on this issue this week. The simplest solution is to pipe the output through `sort -u` to eliminate duplicate HELP. IMHO the real problem is in node_explorer, though. To fix this in `zpool_prometheus` we will need to keep a record of which HELP has already been sent to avoid duplicates. Or perhaps we could just print HELP for the first pool any subsequent pools?

**Comment by richardelling** [comment]
I think this is fixed, can you verify a build with commit 87de63e214c91a66efd2add6a630436d95700872 or later?

**Comment by mrobbert** [comment]
I just built from the master branch and that appears to be working for me.

**Comment by richardelling** [comment]
@mrobbert thanks for testing!
